### ISSUE TITLE
Core Dump Occurs on Program Exit When Using ibm_db in AIX Environment

### ISSUE THREAD

**Issue by k1lowM** [ibmdb/node-ibm_db#1045]
On an AIX environment, when running a Node.js program using the **ibm_db** module, the DB connection and disconnection processes complete successfully, but a core dump always occurs when the program exits.

This issue is reproducible across multiple AIX servers and Node.js versions.

## Test Environment
|OS|Node.js|ibm_db|
|---|---|---|
|AIX 7.2.0.0|v18.12.1|3.1.0|
|AIX 7.3.0.0|v20.18.2|3.1.0|

## Test Code (ibmdbtest.js)
```Javascript
const ibmdb = require('ibm_db');

const connStr = "DRIVER={DB2};DATABASE=xxx;HOSTNAME=xxx.xxx.ibm.com;UID=xxx;PWD=xxx;PORT=xxx";

ibmdb.open(connStr, (err, conn) =&gt; {
  if (err) {
    return console.error('connect error!!:', err);
  }
  console.log('connect success!!');

  conn.close((err) =&gt; {
    if (err) {
      return console.error('close error!!:', err);
    }
    console.log('close success!!');
  });
});
```

## Execution Result
- After running `node ibmdbtest.js > db_test.log 2>&1`, a core dump is generated.
- DB connection and disconnection complete successfully (confirmed via console logs).

## Core Dump Stack Trace (dbx `where` output)
```
.() at 0x0
internal error: unexpected value 120 at line 5201 in file stabstring.c
unnamed block in __cxa_finalize(??), line 69 in "cxa_finalize.c"
__cxa_finalize(??), line 69 in "cxa_finalize.c"
crtcxa.__init_aix_libgcc_cxa_atexit() at 0x10214db54
_GLOBAL__FD_node() at 0x10214dccc
mod_fini1(??, ??) at 0x9fffffff000b410
usl_fini_mods@AF15_11(??, ??, ??, ??, ??) at 0x9fffffff000c82c
usl_exit_fini(??, ??, ??) at 0x9fffffff000b328
usl_exit_fini_mods(??) at 0x9fffffff000c2e8
__modfini64() at 0x900000000001450
exit(??) at 0x90000000005f7d4
```

## Notes
- Changing the version of ibm_db does not resolve the issue.
- This does **not** occur on non-AIX environments (e.g., Linux).

**Comment by bimalkjha** [comment]
@k1lowM We have released ibm_db@4.0.0 with fix of this issue. Please install latest version of ibm_db and verify the fix. Thanks.

**Comment by k1lowM** [comment]
Hi @bimalkjha , 

We tried again with the latest fix applied, but the same core dump is still reproducible, as before.

Environment:
- OS: AIX 7.2.0.0
- Node.js: 18.12.1
- **ibm_db: 4.0.0**

The core dump output is identical to the previous occurrence and happens during Node.js process termination.
(dbx backtrace shows the failure around __cxa_finalize / exit processing.)

```bash
(dbx) where
.() at 0x0
internal error: unexpected value 120 at line 5201 in file stabstring.c
unnamed block in __cxa_finalize(), line 69 in "cxa_finalize.c"
__cxa_finalize()
crtcxa.__init_aix_libgcc_cxa_atexit()
_GLOBAL__FD_node()
mod_fini1()
usl_fini_mods()
usl_exit_fini()
usl_exit_fini_mods()
__modfini64()
exit()
```

We also double-checked whether the correct ibm_db module is being used by comparing 4.0.0 with 3.1.0,
and it appears that the expected module is loaded correctly at runtime.

**Comment by bimalkjha** [comment]
@k1lowM I have executed all test files under ibm_db/test directory on My AIX7.3 system and I do not see any issue. I was able to reproduce same issue before code change, but now I do not see any issue as below:
```
bjha@waldevdbctaix03: nodework/ibm_db/test> uname -a
AIX waldevdbctaix03 3 7 00C6EB514B00
bjha@waldevdbctaix03: nodework/ibm_db/test> node test-connection-object.js
Connection opened successfully
Selected Data =  [ { COL1: 1 } ]
bjha@waldevdbctaix03: nodework/ibm_db/test> node -v
v22.19.0
bjha@waldevdbctaix03: nodework/ibm_db/test>
```
Probably, we can have a Teams meeting to look into your system? Thanks.

**Comment by k1lowM** [comment]
Hi @bimalkjha ,
Thank you for your reply and for the detailed information.
I will first try a few other AIX / Node.js / ibm_db version combinations on my side and then get back to you.

p.s. 
By the way, I am also with IBM Japan.
w3id: Keiichiro.Makiuchi@ibm.com

**Comment by k1lowM** [comment]
Hi @bimalkjha ,
Here is an update from our side based on additional verification.

We have consistently observed core dumps with the following combination, even after properly rebuilding ibm_db on AIX:

- AIX 7.2.0.0
- Node.js v18.12.1
- ibm_db 4.0.0

In this combination, the database connection and close complete successfully, but a core dump always occurs at process exit (around __cxa_finalize), which is the same behavior we observed with ibm_db 3.1.0.

We tried multiple rebuilds of ibm_db 4.0.0 using node-gyp on AIX and also confirmed that the correct module version was being used, but the behavior did not change.

On the other hand, the issue does NOT reproduce with the following combinations:
- AIX 7.2 / 7.3 + Node.js v20.20.1 + ibm_db 4.0.0
- AIX 7.3 + Node.js v22.19.x + ibm_db 4.0.0

Based on these results, upgrading Node.js to v20 or later is currently the only effective workaround we have found.

However, I would like to add some context: in our customer environments, AIX 7.2.0.0 with Node.js v18.12.1 is currently in use, and upgrading Node.js is not always immediately possible.

Given this constraint, we would like to ask whether there is any known workaround, build option, environment variable, or configuration that could avoid or mitigate the core dump specifically on AIX 7.2.0.0 with Node.js v18.12.1 and ibm_db 4.0.0. Any guidance or diagnostic hint would be greatly appreciated.
