### ISSUE TITLE
Returning junk characters for CLOB data

### ISSUE THREAD

**Issue by RjNayak** [ibmdb/node-ibm_db#132]
Hi,
We are using ibm_db node js module to read CLOB data from DB2 source system. We found that when the values contains character more than 514546 (without blanks) then rest of the characters are showing as junk characters such as 䄀䐀䔀开䘀伀刀㸀਀    . We verified these characters are not present in the database and the value in the database in proper . We tried retrieving data for the same query via JDBC and there all the values returned by JDBC are proper with out any junk characters.  Is there any limitations of the CLOB data read for ibm_db driver ? Please help us with this query.

Thanks,

Rajesh

**Comment by rhtpandeyIN** [comment]
Hi @RjNayak thanks for updating us.
wants to know few things:
1) Is It working fine for you less than of mentioned size (<514546) file? 
2) rest of the characters truncated or they are just converted one?
3) are you able to open the new written file after selection from database?
4) and what is the size of new file. Is the size same as the original which you used to insert?

and by observing your comment it seems Insertion working fine as Database is having right value and when you trying to retrieve from JDBC that inserted value (which is inserted by node-ibm_db), you are getting the right things. am I right ?

**Comment by RjNayak** [comment]
Hi rhtpandeyIN,

Please find my comments below.
1) Is It working fine for you less than of mentioned size (<514546) file? Yes. We observed there are some records where the character length is less than 514546 an those are coming as correct in the result.
2) rest of the characters truncated or they are just converted one?- all the characters after the length 514546 are showing as junk characters , hence we are not able to verify whether the data is full or truncated 
3) are you able to open the new written file after selection from database? - I am not writing the CLOB data to any file after retrieval, we pass it to upstream system for handling but if I am logging the result in a file then I can open the file. 
4) and what is the size of new file. Is the size same as the original which you used to insert? The sizes of the file we careted with the data via JDBC and the size of the file we created via Node js ibm_db driver differ by around 100kb.

Regarding data insertion- We are not doing the CLOB data insertion via node js . We are using node js only for retrieval process. The DB2 database and its data is handled by different vendor hence we are not allowed to do insert operation . Our purpose it to only transfer the CLOB data from downstream system to upstream system via node js.

Hopefully, I have answered the queries clearly.

**Comment by rhtpandeyIN** [comment]
hi @RjNayak ,
thanks for clarifications.

Are you using latest code for doing this? let me suggest you, please use below command and install it from github (for the latest code).
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

and if you again facing same problem then please let us update with your sample code.

**Comment by RjNayak** [comment]
Hi rhtpandeyIN,

I tried with the latest code also but still getting the same problem. Following is the sample code we are using

**Query :**
SELECT * FROM (SMS.DOCNO,SMS.XMLDOC,VARCHAR_FORMAT(SMS.RECVTIME,'YYYY-MM-DD')||'T'||VARCHAR_FORMAT(SMS.RECVTIME,'HH:MI:SS.FF3') as RECVTIME,SMS.MSGTYPE, rownumber() over() AS rn FROM SCHEMA1.VIEW1 SMS where DOCTYPE = 6 AND SLNO=208228 AND RECVTIME >= ? and RECVTIME <= ? )tr WHERE tr.rn between ? and ?

**Sample Node Js Code:**

config ="DRIVER={DB2};DATABASE="+database+";HOSTNAME="+hostname+";UID="+username+";PWD="+password+";PORT="+port+";PROTOCOL=TCPIP";
ibmdb = require('ibm_db');
ibmdb.open(config, function (err,conn) {				
			if (!err) {								  
				conn.query(dataQuery,[fromtimestamp,totimestamp,startindex,endindex], function (err, result) {
										
					if (err) {

						log(err);
						return; 

					}
					else {
						var j;

						for(j=0;j<result.length;j++){

								dataArray[j] = result[j];								
						}
						
						//constructing the response object strcuture
						data.ROW=dataArray;
						dataObject.DATA = data;
						returnData.BATCH = dataObject;						
						res.send(returnData);
					
					}					
					conn.close(function () {
												  
					});
				});	

			} else {
					log(err);
					return; 
			}
		});

**Sample Data Base Structure attached:** The XMLDOC column type is CLOB and it can contain characters  >1048576 . 1048576 is the max characters found till now for a particular row.
[SAMPLE DATA.xlsx](https://github.com/ibmdb/node-ibm_db/files/327130/SAMPLE.DATA.xlsx)

Please help us with this issue.

**Comment by bimalkjha** [comment]
@RjNayak We have fixed this issue. Please reinstall again from git using below command and verify:   
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

**Comment by RjNayak** [comment]
Hi bimalkjha,

I installed the latest code but still getting the same issue. Attaching a screens shot for your reference.
![untitled](https://cloud.githubusercontent.com/assets/17158670/16328402/4237f5f4-39f7-11e6-861e-8b6120528e7e.png)

**Comment by bimalkjha** [comment]
can you open your ibm_db/package.json file and confirm that version mentioned at 4th line is: "version": "1.0.0",

**Comment by RjNayak** [comment]
Hi bimalkjha,

Yes the version is showing as "1.0.0".
![image](https://cloud.githubusercontent.com/assets/17158670/16336491/b2c71398-3a2b-11e6-8e79-b47c1c5c4a7c.png)

**Comment by bimalkjha** [comment]
@RjNayak Please use below test program after updating the connection string and file name. It works fine. Also you can see the test/test-blob/insert.js file to know how to work with CLOB/BLOB data.

```
var ibmdb = require("ibm_db")
    , assert = require("assert")
    , fs = require('fs')
    , cn="DATABASE=SAMPLE;HOSTNAME=hotel.torolab.ibm.com;UID=xxxx;PWD=xxxxx;PORT=21169;PROTOCOL=TCPIP"
    , sourcefile = 'trc.flw'
    , targetfile = 'trc2.flw';

ibmdb.open(cn, function (err,conn) {
  if (err) { return console.log(err); }
  try { conn.querySync("drop table mytab"); } catch (e) {};
  try {
    conn.querySync("create table mytab (empId int, trace CLOB(10M))");
    } catch (e) {};
  var text= fs.readFileSync(sourcefile,'ascii');
  var len1 = text.length;
  console.log( "text.length = " + len1);
  conn.prepare("insert into mytab(empId, trace) VALUES (?, ?)", function (err, stmt) {
    if (err) { console.log(err); return conn.closeSync(); }
    var tracefile = {DataType: "CLOB", Data: text};
    stmt.execute([18, tracefile], function (err, result) {
      if( err ) console.log(err);
      else result.closeSync();
      conn.prepare("select * from mytab", function (err, stmt) {
        if(err) { console.log(err); return conn.closeSync(); }
        stmt.execute([], function(err, result) {
          if(err) console.log(err);
          else {
            data = result.fetchAllSync();
            fs.writeFileSync(targetfile, data[0].TRACE, 'ascii');
            result.closeSync();
            var len2 = fs.statSync(targetfile)["size"];
            console.log("Lengths after select = " + len2);
            assert(len1, len2);
          }
        }); });}); });
});
```
If you still face issue, please share your full test program and input file. Thanks.

**Comment by bimalkjha** [comment]
Check [execute](https://github.com/ibmdb/node-ibm_db#executebindingparameters-callback) and [bindingParameters](https://github.com/ibmdb/node-ibm_db#bindingparameters) doc too for detail. Thanks.

**Comment by RjNayak** [comment]
Hi bimlakjha,

I am trying with code given above but getting the below error. Could you please help me with this ?

text.length = 565877
{ [Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
[]
D:\Practice64\db2CLOBTestProgramme\routes\users.js:35
            fs.writeFileSync(targetfile, data[0].TRACE, 'ascii');
                                                ^

TypeError: Cannot read property 'TRACE' of undefined
    at D:\Practice64\db2CLOBTestProgramme\routes\users.js:35:49
    at D:\Practice64\db2CLOBTestProgramme\node_modules\ibm_db\lib\odbc.js:677:11

I am running this partucular code for local DB2 server which is DB2 Express edition as we are not allowed to do data manipulation on client database. We are only allowed for data retrieval.

**Comment by bimalkjha** [comment]
@RjNayak First try afresh below steps:
npm install git+https://git@github.com/ibmdb/node-ibm_db.git
update connection info in test/config.testConnectionStrings.json
run 'node test-blob-insert.js'

If it works for you, put your large file under test/data and rename to trc.fmt. Again run test-blob-insert.js. If all works, update your test accordingly.

If you are using older code, you may get CLI0123E using query or querySync. So, please use the latest code. Thanks.

**Comment by RjNayak** [comment]
Hi bimalkjha,

I followed the instruction given above but when I am trying to run the getting some windows error as show in below screen shot. Is a problem with system or I need to change any configuration?

![image](https://cloud.githubusercontent.com/assets/17158670/16412057/e4924aea-3d47-11e6-80b1-ab506aea6e36.png)

**Comment by bimalkjha** [comment]
@RjNayak I thought you are on non-windows system. For windows, there are some issue and it will be fixed with next release. Wait for 2-3 days. Thanks.

**Comment by bimalkjha** [comment]
Please install latest ibm_db using 'npm install ibm_db'. The fix is released in v1.0.0. Thanks.
