### ISSUE TITLE
Node.js app crashes when sending sending blob to db2 

### ISSUE THREAD

**Issue by rafaeljcuevas** [ibmdb/node-ibm_db#202]
We are getting inconsistent errors. The app fails when we attempt to store file attachments. This issue seems very closely related to issue #141. We don't get a lot of details in the logs but do see this come up after each crash:

ERR *** Error in `node': double free or corruption (!prev): 0x00000000034e67e0 ***

We applied the following recommendations from issue #141:

1) var ibmdb = require('ibm_db');
var pool = new ibmdb.Pool();
...
ibmdb.open();

With these changes, we have noticed a decrease in the failure rate but it is still occurring.

**Comment by bimalkjha** [comment]
@rajocu Please provide steps / test script to reproduce this issue for investigation. Thanks.

**Comment by rajocu** [comment]
I've attached the test script. To reproduce, simply run the node app and upload a document via the web interface. We are unable to reproduce consistently - it's intermittent so please keep that in mind.

[ibmdb2.zip](https://github.com/ibmdb/node-ibm_db/files/662427/ibmdb2.zip)

**Comment by archana-na** [comment]
I have attached the updated test script to reproduce the issue.
The issue is inconsistent and it is observed to occur while uploading certain files(attached).

[ibmdb2App.zip](https://github.com/ibmdb/node-ibm_db/files/670834/ibmdb2App.zip)
![image-1](https://cloud.githubusercontent.com/assets/6279893/21455922/220adc00-c94a-11e6-8df1-9213d1e9cea0.jpg)
![image-2](https://cloud.githubusercontent.com/assets/6279893/21455923/22519dac-c94a-11e6-9629-63c11d34ac79.jpg)

**Comment by archana-na** [comment]
I have attached the updated test script to reproduce the issue.
The issue is inconsistent and it is observed to occur while uploading certain files(attached).

[ibmdb2App.zip](https://github.com/ibmdb/node-ibm_db/files/670834/ibmdb2App.zip)
![image-1](https://cloud.githubusercontent.com/assets/6279893/21455922/220adc00-c94a-11e6-8df1-9213d1e9cea0.jpg)
![image-2](https://cloud.githubusercontent.com/assets/6279893/21455923/22519dac-c94a-11e6-9629-63c11d34ac79.jpg)

**Comment by bimalkjha** [comment]
@archana-na Thanks for uploading the files. we'll try to reproduce using these images and update you.

**Comment by chaitanya11** [comment]
@bimalkjha Do we have any updates on this?

**Comment by bimalkjha** [comment]
@chaitanya11 I am able to run the app and upload file. I tried upload of image-1 more than 100 times, but app never crashed. So, I am unable to repro the issue yet. Any clue what special activity is done in case of crash?? Thanks.

**Comment by gowthamravichandran** [comment]
@bimalkjha  Interesting, I am Gowtham from same team. To get this closed soon,  Can we do a screen share and see what is wrong?

**Comment by bimalkjha** [comment]
yes, please mail me the details on bimaljha@in.ibm.com thanks.

**Comment by bimalkjha** [comment]
As we discussed in todays meeting, please try to save image file locally and then provide the filename to ibm_db for upload as shown in test file https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-file.js . Looking on crash behaviour and error message, it seems after sometime node.exe fails to allocate memory to store the binary file and hence crash in node:malloc.c . The bluemix enviroment has memory constraint and multiple file upload may be consuming all the memory and node.exe fails to allocate new memory. The garbage collector of node.js might be late to free the previously consumed memory. Please use the FILE input method and let us know the update. Thanks.

**Comment by gowthamravichandran** [comment]
@bimalkjha We have tried your solution by storing the file in file system and passing the file to the driver.

It still crashes the app with the following error message,

`J*** Error in `node': corrupted double-linked list: 0x0000000003ba6b60 ***`

Like you said, we are not able to get this error in local. But in bluemix environment.

**Comment by bimalkjha** [comment]
What is the version of node.js in your local system and in bluemix?

**Comment by gowthamravichandran** [comment]
We use NodeJS V6.9.2 in both local and bluemix.

**Comment by gowthamravichandran** [comment]
@bimalkjha Do we have any updates on this.?

**Comment by bimalkjha** [comment]
@gowthamravichandran The reported error is about 'node' and not ibm_db. Seems some bug in node.js code. But, to rule out possibility of any bug in ibm_db, we have added code everywhere to handle error from malloc/calloc call. We have just pushed this code on github. Requesting you to install the latest code using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command and verify the issue. 
Also, I would like to check your new application code that you modified to use `ParamType:"FILE"`. By modifying the application logic, we can try to avoid such error. Thanks.

**Comment by bimalkjha** [comment]
Also, can you check with older node.js? e.g. 4.6.x? to check this issue occur with older node.js also or with recent one only. thanks.

**Comment by gowthamravichandran** [comment]
@bimalkjha after fetching latest code, we experienced even more problems, the app crashed with at different normal select, update queries without any logs.

So we reverted back to 1.0.0. 

While creating this ticket we were using v4.4.x, where we had same issues.

**Comment by bimalkjha** [comment]
@gowthamravichandran have you used ibm_db@1.0.2? We have released it on 17th Jan. Thanks.

**Comment by bimalkjha** [comment]
Fixed in ibm_db@2.0.0. Closing this issue now. Thanks.

**Comment by cvogt** [comment]
@bimaljha what fixed it? Would love to read the commit

**Comment by relatech-teaching** [comment]
Hello, I'm still experiencing this problem using ibm_db@2.0.0
When uploading blob file to db, I get 
`*** Error in 'node': double free or corruption (!prev): 0x0000000003f9c650 ***`

We are using Loopback 2.38.3, ibm_db@2.0.0 on a Cloudfoundry runtime on Bluemix (with OS Ubuntu 14.04 and nodejs 6.10.3) connected to a DashDB for Transtactions instance.

Same version of nodejs, framework and driver on localhost ( running OSX, connected to the same DashDB instance) works nicely. 

I'm able to reproduce the problem in a virtual machine running ubuntu 16.04.

Please let me know if I can help, this is a huge problem for our project at the moment and I'm opening a ticket on Bluemix aswell.
Thanks.

**Comment by sam-github** [comment]
^-- @bnoordhuis did you PR the results from your code review? You saw some memory usage errors, IIRC. cc: @mhdawson

**Comment by fnschroeder** [comment]
We are experiencing the same issue as well. It causes our app to restart shortly after it, but we are not using a Cloud Foundry app, we are using Docker containers with Debian 8.6, node 6.9.2, ibm_db module 2.0.0. Just adding to this as it might help understand the scope of the issue.

**Comment by bnoordhuis** [comment]
@sam-github No, I haven't.

**Comment by gowthamravichandran** [comment]
@bimalkjha updating to 2.0.0 did not solve issues. 

We could also observe that driver crashes with memory error more often when files are edited and uploaded. 

Can you please help us?

**Comment by rhtpandeyIN** [comment]
Hi @bnoordhuis , How you are inserting BLOB data, I mean are you using "FILE" type (https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-file.js) or memory buffer type (https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-insert.js)

it seems while inserting as a "FILE" type some memory access issue is coming : i.e: ->
(refer -> https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-file.js)
var photo = {ParamType:"FILE", DataType: "BLOB", "Data":img1}; 

but if you insert the same as following (Application need to read the file contents and then use as bind parameter.) then this error won't come
(refer -> https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-insert.js)
var photo = {ParamType:1, DataType: "BLOB", "Data":img1};

Please try it once and share the updates.

**Comment by bnoordhuis** [comment]
I don't remember, to be honest.  It's been months since I last looked at the code.

**Comment by rhtpandeyIN** [comment]
OK, No problem.

Well I have given the solution for this issue --> here. #286 
https://github.com/ibmdb/node-ibm_db/issues/286

Please follow this. Thanks

**Comment by bnoordhuis** [comment]
@rhtpandeyIN I think you misunderstand.  It was my and Sam's conclusion after reviewing the C++ code that it has several logic bugs where it frees memory prematurely or writes past the end of the buffer.  You can find some examples + potential fixes here:

bnoordhuis/node-ibm_db@77e7398
bnoordhuis/node-ibm_db@42e24c7

There was much more actually (bnoordhuis/node-ibm_db@c404381) but in that commit it's difficult to separate bug fixes from new code.

I don't have time to pursue this but at least now you know where to look.
