### ISSUE TITLE
blocking behavior

### ISSUE THREAD

**Issue by kevindashgit** [ibmdb/node-ibm_db#210]
using `ibm_db 1.0.1` I'm experiencing some nasty blocking behavior that is easily missed with smaller database sizes - but when I scale it up, I notice that requests come in and are handled sequentially, and the node process is entirely blocked until the request queue is completed.

Actually, I can see that the connection pool size grows and shrinks appropriately with this:
```JavaScript
 setInterval(function() {
  try {debug('current pool size: %s', JSON.stringify(pool.availablePool['[object Object]'].length));} catch(e){}
  }, 500);
```

But the interval is blocked while there are active connections / queries being run (like long-running queries - upwards of 40-60seconds). 

Is this behavior expected? 

I found, that, so far, the only way around this was to add clustering of my node process  which is not an acceptable solution.

Update:
To be more clear - this blocking behavior is only apparent when concurrency increases beyond 1.

**Comment by bimalkjha** [comment]
@kevindashgit Please share some test script to repro and understand the problem. Thanks.

**Comment by kevindashgit** [comment]
@bimaljha I gave you access to it - check your @ibm.com email. Let me know if you need help using it.

**Comment by bimalkjha** [comment]
@kevindashgit I am able to download your codes and run it. When I hit localhost:3000, I always see the consumed time to execute query is around 600ms. How can we achieve more than 1 concurrency for this app on mac?

Also, suggesting you to do following 2 changes in db2.js file:
```
var connectionString = "";  -> line no 9. //Initialise it to empty string.
connectionString = connectionString + key + '=' + connectionObject[key] + ';';
```
In above line, += is changed to =.

From your comment in pull request #123, it seems codes of https://github.com/qpresley/node-ibm_db is working fine for you. Could you please do more testing using https://github.com/qpresley/node-ibm_db and verify the fix? Thanks.

**Comment by liu-jianyang** [comment]
@bimaljha If you're using Chrome, multiple incognito windows will work.

Ok, I'll update.

I was testing this using a long running query (~23 seconds on a single window), and here were the approximate results:
- 2 windows: ~23, ~23.
- 4 windows: ~23, ~23, ~50, ~70
I remember that all the windows returned at the same time (I started them one after the other, and they completed one after the other, at about the same rate).

**Comment by kevindashgit** [comment]
@bimaljha - to make @liu-jianyang's comment more clear - we _did_ find that @qpresley's fork allowed for our test to run concurrently - and perhaps our hope was that we would be getting results back in parallel rather than subsequent requests slowing down (maybe this is expected if things are single-threaded?) - I mean the 2 windows (two requests) seem to complete in parallel - but after that things slow down? Is this expected?

**Comment by bimalkjha** [comment]
Node.js is designed to be single threaded. So, request from node.js application will go on server in sequence only. In this case accumulation of wait time is not expected? I think behaviour of node.js application should be different from behaviour of multithreaded application of other language. Thanks.

**Comment by qpresley** [comment]
There seems to be some misunderstanding in this issue.  First and foremost, the Node.js event loop is single threaded however the Node.js core is a threaded C engine that takes requests from the event loop and processes them.  This means the single process could be running many connections to the back end database simultaneously.

If the application is written such that it takes an end user request and passes it on to the Node core then the event loop should be available to accept a second request which can also be sent to the Node core.

Any slowdown you see is likely either due to the application waiting in the event loop for Node core to respond with results or due to concurrency issues in the C library being executed (ibm_db in this case).  To determine which it is you will likely need to do a significant amount of debugging of both.

**Comment by huineng** [comment]
I agree, as of today IBM_DB2 is no longer useable or needs to be patched by cluster
i run 2 queries in 2 different tabs, i know query one takes 10 seconds and query 2 takes 2 seconds.. i know this running separately  

running them from the tabs (first long then fast one) the fast one will only be executed once the slow one has finished 

our query is as the standard one and pooling makes no difference

**Comment by qpresley** [comment]
Do you have a sample application that shows the issue?  At this point it will be difficult to make changes to the module without knowing exactly where the serialization of the queries is occurring.

**Comment by qpresley** [comment]
@kevindashgit can you also send me a link to your code to try out?

**Comment by huineng** [comment]
reverting back to 1.0.0 solved our problem

**Comment by kevindashgit** [comment]
@qpresley done.

**Comment by qpresley** [comment]
I ran a bunch of tests based on @kevindashgit's app.  It looks like the biggest offender causing overhead is the use of uv_mutex_lock in ODBCConnection::UV_Query.  By using the exclusive locking in this call we are effectively serializing each query to the database.

I can't see a reason why uv_mutex_lock would be used in this function as the resources used should be unique to this execution of this SQL statement.  @bimaljha this looks like one of the first ones that should be reviewed.

**Comment by bimalkjha** [comment]
We'll remove the uv_locks and see how it is working. Thanks.

**Comment by liu-jianyang** [comment]
Hey, I've been testing some more, and it looks like our initial thoughts of using multiple incognito windows were wrong. Chrome will serialize the requests, it seems.

Instead, we tested using curl, and the results seem to be much better:
Without clustering: Started four curl requests at the same time, and they all started and ended at the same time, as should be. Takes ~100 seconds.
With clustering (via pm2): Takes ~23 seconds.

**Comment by bimalkjha** [comment]
@liu-jianyang Using which version of ibm_db you see this behaviour? Is it ibm_db@1.0.2 or latest code from github? Please share the details. Thanks.

**Comment by liu-jianyang** [comment]
Ah sorry, this is the branch that Quentin made. I haven't had the chance to test with the latest published version.

**Comment by qpresley** [comment]
@liu-jianyang note that my branch was merged yesterday so you can try with latest from GitHub now.

**Comment by liu-jianyang** [comment]
Just did some testing with the latest in the master branch:
When I do a fresh run (restarted app, did cache clean on db2), the results were quite promising

- 1 concurrent: 21,753ms
- 2 concurrent: 25,133ms & 25,140ms
- 4 concurrent: 23,539ms & 23,182ms & 23,186ms & 23,192
- 8 concurrent: 38,801ms & 38,813ms & 38,827ms & 38,833ms & 39,248ms. The last 3 started 19s later with 19,643ms & 19,650ms & 19,910ms.
For all of these they started at the same time, and ended at the same time, except for in the 8 concurrent calls, which could be due to system requirements.

However, when I ran again, only flushing the cache for db2 and not restart the app:
- 1 concurrent: 22,098ms
- 2 concurrent: 22,457ms & 53,063ms
- 4 concurrent: 31,280ms & 62,091ms & 86,254ms & 107,943ms
- 8 concurrent: 31,511ms & 61,978ms & 84,984ms & 107,416ms. The last 4 timed out.
For all of these they started at the same time, but the end time increases sequentially, suggesting that they ran sequentially in actuality

**Comment by qpresley** [comment]
Yes, while we may have opened up the concurrency some it does not imply that all blocking issues have been fixed or that the ODBC or database level logic is flowing perfectly.  I'm going to try some more tests of my own but the more example scripts we have that show issues like this the more likely we are to be able to debug them and eliminate them.

**Comment by sam-github** [comment]
cc: @bnoordhuis

**Comment by sam-github** [comment]
@liu-jianyang I think you may be seeing the effects of the default thread pool size, particularly, because you see the issues when you issue more than 4 requests in parallel.

The uv thread pool size is only 4 threads, so if the OCBI thread model is a thread-per-query, you are limited to the size of the thread pool for concurrent queries.

Try running the tests again, and set `UV_THREADPOOL_SIZE`  to what you expect to see for concurrent operations.

**Comment by bmcswee** [comment]
+1 to this. The driver in its current state is totally unusable in an enterprise setting.

Exactly as described by @huineng , running one long query and one short query will force the short query to wait. The work appears to be being performed sequentially.

Also as described by @huineng , rolling back to 1.0.0 fixed the problem. Both 1.0.1 and 1.0.2 appear to have the issue.

**Comment by bimalkjha** [comment]
Thanks @bmcswee . I have pushed code change to fix this issue. Please get the latest code from git and verify it.

**Comment by kevindashgit** [comment]
Hey @bimalkjha I just tested this latest commit - it *does* allow for good concurrency except I still see blocking behavior with longer running queries *_unless_* I bump up `uv_theadpool_size`. I guess my question here is: is this a requirement in order to scale well?

Just to be clear about the unexpected blocking behavior that I'm referring to:
If I run with concurrency set to 12 and request set to 12 for a query that takes 15 seconds:
_expected:_ 15s, 15s, 15s, 15s, 30s, 30s, 30s, 30s, 45s, 45s, 45s, 45s
_actual:_ 45s, 45s, 45s, 45s,45s, 45s,45s, 45s,45s, 45s,45s, 45s

**Comment by qpresley** [comment]
@kevindashgit Each query will still tie up the C thread so if you set the number of worker threads to 12 and you have 12 parallel long running queries then nothing else will get through.  This likely isn't something that can be "fixed" in this module.

**Comment by kevindashgit** [comment]
sure - I kind of expect this to be the case, but I don't quite understand the blocking behavior I'm seeing (like why don't i see "expected" in the example I mentioned in my comment above?)

**Comment by qpresley** [comment]
Yeah, without more information such as a DB2 CLI trace or db2trc on the server it would be tough to say for sure that this is even occurring within the ibm_db module vs. in the database server.   If you have uv_threadpool_size=4 and concurrency/request set to 4 do you get 15s, 15s, 15s, 15s?

**Comment by kevindashgit** [comment]
> If you have uv_threadpool_size=4 and concurrency/request set to 4 do you get 15s, 15s, 15s, 15s?
yes

**Comment by bimalkjha** [comment]
@kevindashgit Yes, to scale well for more than 4 parallel queries you should bump UV_THREADPOOL_SIZE accordingly. The absolute max for UV_THREADPOOL_SIZE is [128](http://docs.libuv.org/en/v1.x/threadpool.html).

If 4 queries are running, each query get executed by default 4 working threads, so nearly same time.
If 8 queries are running, each thread out of 4 default uv thread will have execute 2 queries simultaneously. So, time would be double for each 8 queries.

`expected: 15s, 15s, 15s, 15s, 30s, 30s, 30s, 30s`

In above expectation, you think that until execution of 4 queries finishes, next set of 4 query should not get control of the worker libuv thread. But, it is not the case. Here, each uv thread executes 2 queries simultaneously and hence return result after 15+30=45 second. Because fetching of combine data from server took 45 second.

To be more clear: ODBC API SQLFetch() retrieves only 1 row for each call from server. So, if a query returns 100 rows, ibm_db need to call SQLFetch() 100 times until server tell that there is no more data. Each call of SQLFetch() gets the control of worker libuv thread and releases it. So, if 2 SQL returns 2 rows, the fetch request served by the uv thread would be in following sequence (assuming 8 queries are executed by 4 uv threads, so each thread executes 2 query i.e. thread1 executes 2 query):
```
Fetch row1 for query1 - thread1 took 1s
Fetch row1 for query2 - thread1 took 1s
Fetch row2 for query1 - thread1 took 1s
Fetch row2 for query2 - thread1 took 1s
-- Both query1 and query2 got result simultaneously after 4 sec.
```
Similarly for 16 queries using UV_THREADPOOL_SIZE=4, would return result after 8 sec each. Hope, it explains. Btw, you would observe same behaviour with ibm_db@1.0.0 too. Thanks.

**Comment by bnoordhuis** [comment]
FWIW, I plan on switching node-ibm_db to its own thread pool in due time so that we'll no longer be constrained by libuv's shared thread pool.  Libuv's thread pool is used for things like file operations and DNS queries, so it becomes a bottleneck rather quickly.

That said, I've noticed a few places where we perform potentially blocking work on the main thread instead of in the thread pool.  I intend to address those first.

**Comment by kevindashgit** [comment]
@bimalkjha
> Hope, it explains.
yes that explains it quite nicely thank you!

@bnoordhuis 
>FWIW, I plan on switching node-ibm_db to its own thread pool 
I'd be interested to know how you are planning to do this. At the `C++` level? Or `JavaScript` level (perhaps using something like webworker threads)? 

>That said, I've noticed a few places where we perform potentially blocking work on the main thread instead of in the thread pool. I intend to address those first.
I'd be very interested to know what you dig up!

**Comment by bnoordhuis** [comment]
> I'd be interested to know how you are planning to do this. At the C++ level?

Yes.  Basically a reimplementation of libuv's src/threadpool.c tailored to us.

**Comment by bimalkjha** [comment]
Fixed in ibm_db@2.0.0 release. Thanks.
