### ISSUE TITLE
Can't execute different queries in one single .query() call

### ISSUE THREAD

**Issue by Mouad-B** [ibmdb/node-ibm_db#238]
I can execute many queries of the same type like many selects for exemple in a single connection.query(). I then get an array of result sets. But when putting a delete or insert query before a select, only the delete one will be executed.

This one works fine:

```
ibmdb.open(cn, function (err, conn) {
	if (err) {
		return console.log(err);
	}
    conn.query("select 2 from sysibm.sysdummy1;" +
				"select 3 from sysibm.sysdummy1;"
		, function (err, rows) 
    {
        if (err) {
            console.log(err);
        } else {
            console.log(rows); 
        }
    });
});
```

But this one, will only execute the delete query:

```
ibmdb.open(cn, function (err, conn) {
	if (err) {
		return console.log(err);
	}
    conn.query("delete from xxx WHERE yyyy= 'zzz';" +
				"select 2 from sysibm.sysdummy1;" 
		, function (err, rows) 
    {
        if (err) {
            console.log(err);
        } else {
            console.log(rows);
        }
    });
});
```

**Comment by bimalkjha** [comment]
@Mouad-B conn.query("sql1,sql2,sql3") will not return any result for sql3, if sql2 is not returning any result. Basically, if server tells client that server do have any result to return for an sql passes to conn.query(), conn.query() assumes there is no further results. It seems working as designed. You should update your application logic accordingly. Thanks.

**Comment by Mouad-B** [comment]
So if I do many selects and one of them is empty, all selects after the empty one won't get executed ? Is it designed to work that way ?

**Comment by bimalkjha** [comment]
@Mouad-B We have pushed the fix of this issue to github. Please install the latest code from git using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` on non-windows platform and test it. For windows, you have to wait till next release. Thanks.

**Comment by Mouad-B** [comment]
Hi,
I just retested and the issue remains.. Whenever I put a select query with empty results in my list of queries, it stops there and I get no more results.
Should I specify a version of the module or git+https://git@github.com/ibmdb/node-ibm_db.git is enough ?
Thank you for your support !

**Comment by bimalkjha** [comment]
@Mouad-B Just run below steps:
npm install git+https://git@github.com/ibmdb/node-ibm_db.git 
cd ibm_db/test
vi config.testConnectionStrings.json and update connection information.
node test-basic-test.js

In test file test-basic-test.js executes 3 SQLs out of which second query is not returning any result. This sql returns 2 result sets. It it works for you, please modify it to reproduce your problem and share the test script with us. Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @Mouad-B , are you still facing this issue or it got resolved with the latest code changes? Please do share your experience thanks.
