### ISSUE TITLE
segfault if connection is interrupted

### ISSUE THREAD

**Issue by rmg** [ibmdb/node-ibm_db#259]
If the process exits after a connection has been initiated but _before_ it has been established, there is a segfault.

Here is a reduced reproduction, which is just a modified version of the example code given in `README.md`:

```js
var ibmdb = require('ibm_db');

var connStr = "DATABASE=<dbname>;HOSTNAME=<myhost>;UID=db2user;PWD=password;PORT=<dbport>;PROTOCOL=TCPIP";

ibmdb.open(connStr, function (err,conn) {
  // exiting before this causes the segfault
  console.error('connected?', err || true);
});

function earlyExit() {
  console.error('exiting early');
  process.exit();
}

// in the future, after the connection is initialized, but before the
// connection has a chance to be established.
setImmediate(earlyExit);
```

Found when disabling all tests in strongloop/loopback-connector-db2#98.

**Comment by rhtpandeyIN** [comment]
Hi @rmg , Is there any updated related to this issue? I just checked the referenced issues and some fix has been merged there. Do we need to do something here from our side or this is application related issue?

**Comment by rhtpandeyIN** [comment]
Hi, I ran the provided repro test case around 10 times, but I am not getting any segfault error. Below is the output: (I am using localhost connection)

$ node rht.js
exiting early

$ node rht.js
exiting early

$ node rht.js
exiting early

$ node rht.js
exiting early

$ node rht.js
exiting early

$ node rht.js
exiting early

$ node rht.js
exiting early

$ node rht.js
exiting early

**Comment by rmg** [comment]
This is still reproducible for me. I am testing on macOS connecting to a remote DB2 instance.

**Comment by bimalkjha** [comment]
@rmg How are you exiting a connection after it has been initiated but before it has been established?
I am too on macOS connecting to a remote DB2 instance. Just after half second of `node test/test-basic-test.js`, I press Ctrl+C and program terminated without any error:
```
/Users/bimaljha/nodework/master/ibm_db2/test> node test-basic-test.js 
Trying to open a connection ... 
^C
/Users/bimaljha/nodework/master/ibm_db2/test> 
```
I tried multiple times without any success. Please share more info to reproduce it.

Thanks.

**Comment by rmg** [comment]
@bimaljha run the code in the issue description, it replicates the conditions. You just need to use a real connection string instead of the placeholder that is there.

**Comment by bimalkjha** [comment]
Crash is happening in ODBC/CLI library libdb2.so.1. Here is the stack trace that I got using gdb:
```
ODBC::UV_AfterCreateConnection - Exit
exiting early

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdeffd700 (LWP 79183)]
0x00007fffe6491ee9 in CLI_callbDrdaInput(db2UCinterface*) ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
(gdb) where
#0  0x00007fffe6491ee9 in CLI_callbDrdaInput(db2UCinterface*) ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#1  0x00007fffe6d42b78 in sqljrGenSqlDta(db2UCinterface*, unsigned int) ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#2  0x00007fffe6d68ef6 in sqljrDrdaArCall(db2UCinterface*, UCstpInfo*) ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#3  0x00007fffe670e2cf in sqleuInvokeActivationRoutine(db2UCconHandle*, SQLEU_UDFSP_ARGS*, sqlca*, bool, unsigned int) ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#4  0x00007fffe670bc1f in sqleuPerformServerActivationCheck(db2UCconHandle*, sqlca*) () from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#5  0x00007fffe670a5b7 in sqleUCappConnect ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#6  0x00007fffe6596f20 in CLI_sqlConnect(CLI_CONNECTINFO*, sqlca*, CLI_ERRORHEADERINFO*) () from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#7  0x00007fffe653f812 in SQLConnect2(CLI_CONNECTINFO*, unsigned char*, short, unsigned char*, short, unsigned char*, short, unsigned char*, short, unsigned char) () from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#8  0x00007fffe655719f in SQLDriverConnect2(CLI_CONNECTINFO*, void*, unsigned char*, short, unsigned char*, short, short*, unsigned short, unsigned char, unsigned char, CLI_ERRORHEADERINFO*) ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#9  0x00007fffe652ee43 in SQLDriverConnect ()
   from /home/bjha/nodework/clidriver/lib/libdb2.so.1
#10 0x00007ffff49a5ea1 in ODBCConnection::UV_Open(uv_work_s*) ()
    at ../src/odbc_connection.cpp:256
#11 0x00000000009bed81 in worker (arg=0x0) at ../deps/uv/src/threadpool.c:83
#12 0x00007ffff6f98184 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007ffff6cc503d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)
```
It seems outside the scope of ibm_db driver and a negative scenario too. Hence, closing the issue. Thanks.

**Comment by rmg** [comment]
@bimalkjha is there an upstream issue opened for investigating/fixing this in `libdb2`?
