### ISSUE TITLE
Version 2.6.0 Memory Leak

### ISSUE THREAD

**Issue by UHCFurin** [ibmdb/node-ibm_db#567]
I've been using ibm_db for a few years now in a few applications without problems. I had my package.json set to use the latest version of ibm_db, which worked great for me until version 2.6.0. When 2.6.0 released, suddenly my application quickly ran out of memory, every time it rebooted it ran out of memory again. I spent 2 days reverting code and analyzing my own memory usage, until I realized it wasn't caused by something my team had done, but rather something in this new build of ibm_db. As soon as I reverted my package.json file back to version 2.5.3 the memory leak went away.
I use the `query` function with connection pools.

**Comment by bimalkjha** [comment]
@UHCFurin We have just pushed the fix for issue on github. Please install the latest code using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command and verify it. After verification, we can release a new version. Thanks.

**Comment by bol07** [comment]
@bimalkjha Does this happen under a specific case? Trying to determine which version of the package to use and we were planning to go with 2.6.0. Any suggestions?
Also, when is the new version scheduled to release with the fix for this issue?

**Comment by bol07** [comment]
@bimalkjha If we have maxpoolsize set, would it prevent the above issue or it might still occur?

**Comment by bimalkjha** [comment]
@bol07 Just wait for 2-3 days. We have plan to release a new version 2.6.1 by 4th September that will include fix of this issue. Latest commit has fixed all memory leak issues. Thanks.

**Comment by bimalkjha** [comment]
@UHCFurin @bol07 ibm_db@2.6.1 include fix for this issue. Please install latest ibm_db version 2.6.1 and verify it. Thanks.

**Comment by wahlbergfredrik** [comment]
I've also had issues with memory leaks since the release of v2.6.0. Reverting back to v2.5.3 resolved the memory leak issues. 
Unfortunately v2.6.1 doesn't seem to resolve all the memory leak issues for us. With v2.5.3, our application runs fine without any memory leak issues. With v2.6.0, it crashes due to memory leak issues after ~20min and with v2.6.1 it crashes due to memory leak issues after ~30min. 
There seems like some issues have been resolved (as it takes longer for the memory leak to crash the application), but unfortunately not all, as the application still crashes.

Should there be an additional bug raised for the remaining memory leaks in v2.6.1?

**Comment by bimalkjha** [comment]
@wahlbergfredrik ibm_db@2.6.0 started using non-deprecated new APIs of node.js v11 and v12. I can see few memory leak issues reported for node.js: https://github.com/nodejs/node/issues/28420
I have installed valgrind and ran command `valgrind -v --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes node test/test-basic-test.js` after updating connection information in `test/config.testConnectionStrings.json` file to find memory leaks and fixed the ibm_db related memory leaks. I do not see any further memory leak in ibm_db. valgrind reports few issues in ibm_db as warning and that should be ok if application frees the statement and connection object at end.
I would request you to share some test program using which I can reproduce your problem and look into it. Thanks.

**Comment by wahlbergfredrik** [comment]
We're still using Node v10. Is v11 or v12 recommended for ibm_db@2.6.0/2.6.1 given these changes?

**Comment by hiro5id** [comment]
I'm using v2.6.1 with node v10 and we are most definitely experiencing a memory leak.  Our app is constantly having to restart in order to be able to query via ibm_db driver.
